//! DATA THAT WILL BE USED IN THE CONSTRUCTION OF THE PROJECT

interface Data {
  //! THE NAME THAT THE USER WRITES, THIS IS THE NAME THAT WILL BE USED TO CREATE THE PROJECT AND THE FOLDER
  name: string;
}

export { Data };
