name: templates

on:
  push:
    branches: ['main', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check local install
        run: node ./ci/checkLocalInstall.js
